## ML (Using Pycaret) Workflow:
<input type="checkbox" checked id="option1" name="option1" value="yes">
<label for="option1">Import necessary libraries.</label>
<br />
<input type="checkbox" checked id="option2" name="option2" value="yes">
<label for="option2">Reading transformed dataset.</label>
<br />
<input type="checkbox" checked id="option3" name="option3" value="yes">
<label for="option3">Creating the best model with Pycaret and make prediction with that (with help of chatgpt).</label>
<br />

In [1]:
import pandas as pd
import numpy as np
from pycaret.regression import *
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [2]:
df = pd.read_excel("data transformed/data.xlsx")

In [3]:
df.head(3)

   Area  Room  Parking  Warehouse  Elevator       Price  outlier
0    63     1     True       True      True  1850000000    False
1    60     1     True       True      True  1850000000    False
2    79     2     True       True      True   550000000    False

In [5]:
X = df[["Area","Room","Parking","Warehouse","Elevator"]]
y = df["Price"]


new_df = X.copy()
new_df["Price"] = y

In [6]:
reg = setup(data=new_df,target="Price",session_id=42,train_size=0.7,normalize=True)

In [7]:
best_model = compare_models()

In [9]:
et_model = create_model("et")

In [12]:
train_predictions = predict_model(et_model,data=get_config("X_train"))
y_train = get_config("y_train")
y_train_pred = train_predictions["prediction_label"]


test_predictions = predict_model(et_model)
y_test = test_predictions["Price"]
y_test_pred = test_predictions["prediction_label"]

In [13]:
r2_score_train = r2_score(y_train, y_train_pred)
r2_score_test = r2_score(y_test, y_test_pred)

r2_gap = r2_score_train - r2_score_test

mae = mean_absolute_error(y_test, y_test_pred)
mse = mean_squared_error(y_test, y_test_pred)
rmse = np.sqrt(mse)

In [15]:
print(f"r2_score of train data: {r2_score_train:,.2f}")
print(f"r2_score of test data: {r2_score_test:,.2f}")
print(f"Gap between train and test: {r2_score_train - r2_score_test:,.2f}\n")

print(f"MAE: {mae:,.0f}")
print(f"MSE: {mse:,.0f}")
print(f"RMSE: {rmse:,.0f}")

r2_score of train data: 0.59
r2_score of test data: 0.54
Gap between train and test: 0.05

MAE: 1,358,306,431
MSE: 3,808,929,748,922,541,568
RMSE: 1,951,647,957

In [17]:
final_et_model = finalize_model(et_model)

In [24]:
unseen_data = pd.DataFrame({"Area":[50,45,70],
                           "Room":[2,1,2],
                           "Parking":[0,1,1],
                           "Warehouse":[1,1,1],
                           "Elevator":[0,1,1]})

predictions = predict_model(
    final_et_model,
    data=unseen_data
)

predictions

   Area  Room  Parking  Warehouse  Elevator  prediction_label
0    50     2        0          1         0      9.456802e+08
1    45     1        1          1         1      1.597847e+09
2    70     2        1          1         1      2.405209e+09