In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl

In [3]:
df = pd.read_csv("dataset/customer_shopping_data.csv")
df["revenue"] = df["quantity"] * df["price"]
df["invoice_date"] = pd.to_datetime(df["invoice_date"],format='mixed')

In [4]:
df.head(3)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,revenue
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-05-08,Kanyon,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-09-11,Metrocity,300.08

In [24]:
days = df["invoice_date"].max() - df["invoice_date"].min()
print(f"Total days of report: {days}")
# It's about 3 years!

Total days of report: 1065 days 00:00:00

# Customers

##### Number of customers

In [29]:
df["customer_id"].nunique()

99457

##### Customer gender

In [5]:
gender = df.groupby(["gender"],as_index=False).agg(
    count_of_gender = ("gender","count")
)

gender

   gender  count_of_gender
0  Female            59482
1    Male            39975

##### Customer age

In [6]:
df["age_group"] = df["age"].map(lambda x: "[0-14] -> Children" if x<15 
                                    else "[15-24] -> Youth" if x<26 
                                    else "[25-64] -> Adults" if x<65 
                                    else "[65-99] -> Older Adults")

age_group = df.groupby(["age_group"],as_index=False).agg(
    age_groups = ("age_group","count")
).sort_values(by="age_groups",ascending=False).reset_index(drop=True)

age_group

                 age_group  age_groups
0        [25-64] -> Adults       74671
1         [15-24] -> Youth       15359
2  [65-99] -> Older Adults        9427

##### Top 10 customers based on sales performance

In [18]:
snapshot_date = pd.Timestamp("2024-01-01")

rfm_table = df.groupby(["customer_id"],as_index=False).agg(
    Recency = ("invoice_date",lambda x: (snapshot_date - x.max()).days),
    Frequency = ("quantity","sum"),
    Monetary = ("revenue","sum")
).sort_values(by="Recency",ascending=False)

rfm_table["R"] = pd.qcut(rfm_table["Recency"].rank(method="first",ascending=True),5,labels=[5,4,3,2,1]).astype(int)
rfm_table["F"] = pd.qcut(rfm_table["Frequency"].rank(method="first",ascending=True),5,labels=[1,2,3,4,5]).astype(int)
rfm_table["M"] = pd.qcut(rfm_table["Monetary"].rank(method="first",ascending=True),5,labels=[1,2,3,4,5]).astype(int)

rfm_table["Weighted_RFM_Score"] = ( rfm_table["R"] * 0.40 + rfm_table["F"] * 0.30 + rfm_table["M"] * 0.30 ).round(2)

rfm_table["Segment"] = pd.cut( rfm_table["Weighted_RFM_Score"], bins=[0, 2, 3, 4, 5],
    labels=[
        "At Risk/Lost",
        "Potential Customers",
        "Loyal Customers",
        "Champions"
    ],
    include_lowest=True
)

rfm_table = rfm_table.sort_values(by="Weighted_RFM_Score",ascending=False).reset_index(drop=True)

rfm_table.head(3)

,customer_id,Recency,Frequency,Monetary,R,F,M,Weighted_RFM_Score,Segment
0,C241132,428,5,26250.0,5,5,5,5.0,Champions
1,C196732,447,5,7502.0,5,5,5,5.0,Champions
2,C179174,365,5,7502.0,5,5,5,5.0,Champions

##### Customers loyalty over the past years
<p>Minimum of date: 2021-01-01</p>
<p>Maximum of date: 2023-12-02</p>

In [16]:
customer_loyalty = df.copy()

customer_loyalty["invoice_year"] = customer_loyalty["invoice_date"].dt.strftime("%Y")

loyalty = customer_loyalty.groupby(["customer_id","invoice_year"],as_index=False).agg(
    customer_exists = ("invoice_year","nunique")
).sort_values(by="customer_id",ascending=False).reset_index(drop=True)

loyalty.head(3)

  customer_id invoice_year  customer_exists
0     C999995         2021                1
1     C999976         2022                1
2     C999974         2022                1

##### Customers buying pattern by shopping mall,payment and amount

In [14]:
shopping_mall_data = df.copy()

shopping_mall = shopping_mall_data.groupby(["customer_id","shopping_mall","payment_method"],as_index=False).agg(
    total_revenue = ("revenue","sum")
).sort_values(by="customer_id",ascending=False).reset_index(drop=True)

shopping_mall.head(3)

  customer_id   shopping_mall payment_method  total_revenue
0     C999995          Kanyon           Cash        1200.32
1     C999976       Metrocity     Debit Card         322.56
2     C999974  Forum Istanbul           Cash        7502.00

##### Total sales and quantity

In [37]:
print(f"Sum of Revenue: {df.revenue.sum():,.2f}$")
print(f"Sum of Quantity: {df.quantity.sum():,.0f}")

Sum of Revenue: 251,505,794.25$
Sum of Quantity: 298,712

In [38]:
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall', 'revenue',
       'age_group'],
      dtype='object')

##### Revenue per product

In [44]:
product_revenue = df.groupby(["category"],as_index=False).agg(
    Revenue = ("revenue","sum")
).sort_values(by="Revenue",ascending=False).reset_index(drop=True)

product_revenue["Revenue"] = product_revenue["Revenue"].map(lambda x:f"{x:,.2f}")

product_revenue

          category         Revenue
0         Clothing  113,996,791.04
1            Shoes   66,553,451.47
2       Technology   57,862,350.00
3        Cosmetics    6,792,862.90
4             Toys    3,980,426.24
5  Food & Beverage      849,535.05
6            Books      834,552.90
7         Souvenir      635,824.65